#!/bin/zsh

# Get the console user (if any)
CONSOLE_USER=$(stat -f '%Su' /dev/console)
CONSOLE_UID=$(id -u "$CONSOLE_USER")

# LaunchAgent #
if [[ "$CONSOLE_USER" != "root" && "$CONSOLE_USER" != "_mbsetupuser" && -n "$CONSOLE_UID" ]]; then
    # Remove any old instance first
    launchctl bootout "gui/$CONSOLE_UID" "/Library/LaunchAgents/fr.jeremyb.sumb.plist" 2>/dev/null
    
    # Kill SUMB if still running
	if pgrep -x "SUMB"; then
		killall -9 "SUMB"
	fi
fi

exit 0
